MUSCLE (3.8) multiple sequence alignment


sp|Q9BYF1|ACE2_HUMAN        MSSSSWLLLSLVAVTAAQSTIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNTNITEENVQ
tr|G3QWX4|G3QWX4_GORGO      MSGSSWLLLSLVAVTAAQSTIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNTNITEENVQ
                            **.*********************************************************

sp|Q9BYF1|ACE2_HUMAN        NMNNAGDKWSAFLKEQSTLAQMYPLQEIQNLTVKLQLQALQQNGSSVLSEDKSKRLNTIL
tr|G3QWX4|G3QWX4_GORGO      NMNNAGDKWSAFLKEQSTLAQMYPLQEIQNLTIKLQLQALQQNGSSVLSEDKSKRLNTIL
                            ********************************:***************************

sp|Q9BYF1|ACE2_HUMAN        NTMSTIYSTGKVCNPDNPQECLLLEPGLNEIMANSLDYNERLWAWESWRSEVGKQLRPLY
tr|G3QWX4|G3QWX4_GORGO      NTMSTIYSTGKVCNPNNPQECLLLEPGLNEIMANSLDYSERLWAWESWRSEVGKQLRPLY
                            ***************:**********************.*********************

sp|Q9BYF1|ACE2_HUMAN        EEYVVLKNEMARANHYEDYGDYWRGDYEVNGVDGYDYSRGQLIEDVEHTFEEIKPLYEHL
tr|G3QWX4|G3QWX4_GORGO      EEYVVLKNEMARANHYEDYGDYWRGDYEVNGVDGYDYSRGQLIEDVEHTFEEIKPLYEHL
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        HAYVRAKLMNAYPSYISPIGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNIDVTDAMVDQ
tr|G3QWX4|G3QWX4_GORGO      HAYVRAKLMNAYPSYISPIGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNIDVTDAMVDQ
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        AWDAQRIFKEAEKFFVSVGLPNMTQGFWENSMLTDPGNVQKAVCHPTAWDLGKGDFRILM
tr|G3QWX4|G3QWX4_GORGO      AWDAQRIFKEAEKFFVSVGLPNMTQGFWENSMLTDPGNVQKAVCHPTAWDLGKGDFRILM
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        CTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSLSAATPKHLKS
tr|G3QWX4|G3QWX4_GORGO      CTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSLSAATPKHLKS
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        IGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPKDQWMKKWWEM
tr|G3QWX4|G3QWX4_GORGO      IGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPKDQWMKKWWEM
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        KREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALCQAAKHEGPLH
tr|G3QWX4|G3QWX4_GORGO      KREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALCQAAKHEGPLH
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        KCDISNSTEAGQKLFNMLRLGKSEPWTLALENVVGAKNMNVRPLLNYFEPLFTWLKDQNK
tr|G3QWX4|G3QWX4_GORGO      KCDISNSTEAGQKLFNMLRLGKSEPWTLALENVVGAKNMNVRPLLNYFEPLFTWLKDQNK
                            ************************************************************

sp|Q9BYF1|ACE2_HUMAN        NSFVGWSTDWSPYADQSIKVRISLKSALGDKAYEWNDNEMYLFRSSVAYAMRQYFLKVKN
tr|G3QWX4|G3QWX4_GORGO      NSFVGWSTDWSPYADQSIKVRISLKSALGDKAYEWNDNEMYLFRSSVAYAMRQYFLEVKK
                            ********************************************************:**:

sp|Q9BYF1|ACE2_HUMAN        QMILFGEEDVRVANLKPRISFNFFVTAPKNVSDIIPRTEVEKAIRMSRSRINDAFRLNDN
tr|G3QWX4|G3QWX4_GORGO      QMILFGEEDVRVANLKPRISFNFFVTAPKNVSDIIPRTEVEKAIRMSRGRINDAFRLNDN
                            ************************************************.***********

sp|Q9BYF1|ACE2_HUMAN        SLEFLGIQPTLGPPNQPPVSIWLIVFGVVMGVIVVGIVILIFTGIRDRKKKNKARSGENP
tr|G3QWX4|G3QWX4_GORGO      SLEFLGIQPTLGPPNQPPVSIWLIVFGVVMGVIVVGIVILIFTGIRDRKKKNKARSEENP
                            ******************************************************** ***

sp|Q9BYF1|ACE2_HUMAN        YASIDISKGENNPGFQNTDDVQTSF
tr|G3QWX4|G3QWX4_GORGO      YASIDISKGENNPGFQNTDDVQTSF
                            *************************
